import Foundation
import XCTest
@testable import SpiekCore

/// Reference values generated by running the original `spiek_8.html`
/// JavaScript in Node. If these pass, the Swift port is byte-compatible with
/// the web app — same addresses, same signatures, same on-chain records.
enum Vectors {
    static let root: [String: Any] = {
        guard let url = Bundle.module.url(forResource: "vectors", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            XCTFail("vectors.json is missing from the test bundle")
            return [:]
        }
        return object
    }()

    static func list(_ key: String) -> [[String: Any]] {
        root[key] as? [[String: Any]] ?? []
    }

    static func dictionary(_ key: String) -> [String: Any] {
        root[key] as? [String: Any] ?? [:]
    }
}

extension Dictionary where Key == String, Value == Any {
    func string(_ key: String) -> String { self[key] as? String ?? "" }
    func optionalString(_ key: String) -> String? { self[key] as? String }
    func int(_ key: String) -> Int { (self[key] as? NSNumber)?.intValue ?? 0 }
    func uint64(_ key: String) -> UInt64 { (self[key] as? NSNumber)?.uint64Value ?? 0 }
    func double(_ key: String) -> Double { (self[key] as? NSNumber)?.doubleValue ?? 0 }
    func bool(_ key: String) -> Bool { (self[key] as? NSNumber)?.boolValue ?? false }
    func bytes(_ key: String) -> [UInt8] { Hex.decode(string(key)) ?? [] }
}
